# Generated by Django 6.1 on 2026-09-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.DecimalField()),
                ("estimated_prep_minutes", models.PositiveIntegerField()),
                ("is_available", models.BooleanField(default=True)),
            ],
        ),
    ]
