# Generated by Django 6.1 on 2026-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_order_orderitem_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="menu_items/"),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
