# Generated by Django 6.1 on 2026-09-10 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("waiter", "Waiter"),
                    ("chef", "Chef"),
                ],
                default="customer",
                max_length=10,
            ),
        ),
    ]
